-- Proširena lista kategorija majstora (usluge na platformi)
INSERT INTO categories (name, slug, base_token_cost) VALUES
('Agencija za čišćenje', 'agencija-za-ciscenje', 1),
('Asfaltiranje', 'asfaltiranje', 2),
('Behaton ploče, popločavanje', 'behaton-plocice-poplocavanje', 2),
('Bravarija, bravarske usluge', 'bravarija-bravarske-usluge', 2),
('Bušenje bunara', 'busenje-bunara', 3),
('Cementna košuljica, ravnajući sloj, estrih', 'cementna-kosuljica-estrih', 2),
('Čišćenje dimnjaka', 'ciscenje-dimnjaka', 1),
('Drveni prozori', 'drveni-prozori', 2),
('Elektroinstalacije, električar', 'elektroinstalacije-elektricar', 2),
('Fasade', 'fasade', 2),
('Geomehanika', 'geomehanika', 3),
('Geometar, geodeta', 'geometar-geodeta', 2),
('Gipsarski radovi', 'gipsarski-radovi', 2),
('Građevinski radovi', 'gradjevinski-radovi-nove', 3),
('Kamenorezac, klesar', 'kamenorezac-klesar', 2),
('Keramika, keramičar', 'keramika-keramicar', 2),
('Klima-uređaji, ugradnja klime', 'klima-uredjaji-ugradnja-klime', 2),
('Kontejneri za stanovanje', 'kontejneri-za-stanovanje', 3),
('Krečenje, moler', 'krecenje-moler', 1),
('Laminati', 'laminati', 1),
('Lepljenje pločica', 'lepljenje-plocica', 1),
('Limarski radovi', 'limarski-radovi', 2),
('Majstori za krov', 'majstori-za-krov', 2),
('Mašinsko malterisanje', 'masinsko-malterisanje', 2),
('Metalne konstrukcije', 'metalne-konstrukcije', 3),
('Montažne kuće', 'montazne-kuce', 3),
('Nameštaj po meri', 'namestaj-po-meri', 2),
('Obnova drvenih prozora', 'obnova-drvenih-prozora', 2),
('Parketari', 'parketari', 2),
('Pranje dvorišta, fasade, krova', 'pranje-dvorista-fasade-krova', 1),
('PVC prozori', 'pvc-prozori', 2),
('Renoviranje kupatila', 'renoviranje-kupatila', 2),
('Renoviranje stana', 'renoviranje-stana', 3),
('Selidbe', 'selidbe', 1),
('Sobna vrata', 'sobna-vrata', 1),
('Staklo, staklorezac', 'staklo-staklorezac', 2),
('Stolar', 'stolar', 2),
('Tapaciranje nameštaja', 'tapaciranje-namestaja', 1),
('Temelj, temeljna ploča', 'temelj-temeljna-ploca', 3),
('Toplotne pumpe', 'toplotne-pumpe', 2),
('Ulazna vrata', 'ulazna-vrata', 2),
('Vodoinstalater', 'vodoinstalater', 2),
('Drugo', 'drugo', 1)
ON CONFLICT (slug) DO NOTHING;
